### ISSUE TITLE
TypeError: Cannot read property 'isProgram' of undefined

### ISSUE THREAD

**Issue by umebfl** [shuerguo999/gogoAST#1]
const AST = GG.createAstObj(content, defaultOptions)

    AST.replaceSelBySel('const $_$ = require($_$)', 'import $_$ from $_$');
    
    const result = AST.generate()

    // error
    buildAstByAstStr(str, astPatialMap = {}, { isProgram = false, parseOptions }) {
                                               ^
    TypeError: Cannot read property 'isProgram' of undefined

**Comment by shuerguo999** [comment]
Please use the latest version:  https://github.com/thx/gogocode ~
